version: '3.12.7'
 
services:
 
  SCM:
    image: sandhya250/app:latest
    ports:
      - "8000:8000"
 
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    depends_on:
      - SCM
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
 
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx1G  
    depends_on:
      - zookeeper
 
  servers:
    image: sandhya250/server:latest
    ports:
      - "12345:12345"
    depends_on:
      - kafka
 
  producer:
    image: sandhya250/producer:latest
    depends_on:
      - servers
 
  consumer:
    image: sandhya250/consumer:latest
    depends_on:
      - producer