version: '3.9'
 
services:
  backend:
    build:
      context: .  
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app  
    depends_on:
      - kafka  
 
  frontend:
    build:
      context: ./frontend 
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
 
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-network
 
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx1G  
    networks:
      - app-network
    depends_on:
      - zookeeper
 
  servers:
    image: sandhya250/server:latest
    ports:
      - "12345:12345"
    depends_on:
      - kafka
    networks:
      - app-network
 
  producer:
    image: sandhya250/producer:latest
    depends_on:
      - servers
    networks:
      - app-network
 
  consumer:
    image: sandhya250/consumer:latest
    depends_on:
      - producer
    networks:
      - app-network
 
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=SCMXpertLite
    networks:
      - app-network
 
networks:
  app-network:
    driver: bridge